package msquerybuilderbackend.business;

import java.util.HashMap;

import org.neo4j.ogm.model.Result;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.neo4j.template.Neo4jOperations;
import org.springframework.data.neo4j.template.Neo4jTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
/**
 *  Class for all activities with neo4j database regarding the Nodetypes in the neo4j database
 *  
 * @author drago
 *
 */
@Component
public class NodeTypeBusiness {

	@Autowired
	Neo4jOperations neo4jOperations;
	Neo4jTemplate temp;
	
	/**
	 * method which queries all nodetypes in neo4j excluding the nodetypes generated by our application
	 * @return a Result with the queried nodetypes
	 */
	public Result getNodeTypes(){
		
		String queryNodes = "MATCH (n) WHERE labels(n) <> \"ExpertQuery\" AND labels(n) <> \"Parameter\" "
				+ "AND labels(n)<>\"Alert\" AND labels(n)<>\"Category\" AND labels(n) <> "
				+ "\"QueryBuilderJsonStringObject\" AND labels(n) <> \"User\" AND labels(n) <> \"UserAuthority\" return DISTINCT labels(n) AS Label";
	
		Result result = neo4jOperations.query(queryNodes, new HashMap<String, String>());
	
		return result;
	}
	
	/**
	 * method which queries nodetypes which are on the other end of a given relationship and a given direction and a given nodetype 
	 * @param nodeId is the nodetype on the one side of the relationship
	 * @param relationship is the relationshiptype
	 * @param direction is the direction (ingoing/outgoing)
	 * @return a Result of the queried nodetypes which fulfill the given conditions
	 */
	public Result getNodeTypesWithCertainRelationshipAndDirection(String nodeId, String relationship, String direction){
		String queryNodes="";
		if (direction.equals("ingoing")){
			 queryNodes = "MATCH (n:" + nodeId + ") <-["+relationship+"]- (p) return distinct labels(p) AS Label";
			 
		} else {
			queryNodes = "MATCH (n:" + nodeId + ") -["+relationship+"] -> (p) return distinct labels(p) AS Label";
		}
		

		Result result = neo4jOperations.query(queryNodes, new HashMap<String, String>());
		
		return result;
	}
	
	/**
	 * method which queries nodetypes which are on the other end of a given relationship and a given nodetype
	 * @param nodeId is the nodetype on the one side of the relationship
	 * @param relationship is the relationshiptype
	 * @return a Result of the queried nodetypes which fufill the given conditions
	 */
	public Result getNodeTypesWithCertainRelationship(String nodeId, String relationship){
		String	queryNodes = "MATCH (n:" + nodeId + ") -[f:"+relationship+"] -> (p) return distinct labels(p) AS Label";
		Result result = neo4jOperations.query(queryNodes, new HashMap<String, String>());	
		return result;
	}
	
	/**
	 * method which queries the keys (attributes) of a give nodetype
	 * @param nodeId is the nodetype for which the keys are queried
	 * @return a Result of the keys found for this nodetype
	 */
	public Result getKeysOfCertainNodeType(String nodeId){
		
		String queryKeys = "MATCH (n:" + nodeId + ") UNWIND keys(n) AS key " +
						 "WITH key ORDER BY key RETURN  COLLECT(distinct key) as Keys";

		Result result = neo4jOperations.query(queryKeys, new HashMap<String, String>());
		
		return result;
	}
	
	/**
	 * method which queries all relationshiptypes of a certain nodetype and a given direction
	 * @param nodeId is the nodetype for which the relationshiptypes are queried
	 * @param direction is the direction the relationshiptypes must fulfill (ingoig/outgoing)
	 * @return a Result of relationshiptypes with the given parameter
	 */
	public Result getRelationsOfNodeTypeWithDirection(String nodeId, String direction){
		String queryRelations="";
		if (direction.equals("ingoing")||direction.equals("INGOING")){
			queryRelations = "MATCH (n:" + nodeId + ")<-[r]- (p) return distinct type(r) AS Relation, labels(p) as Labels";	
		} else if (direction.equals("outgoing") || direction.equals("OUTGOING")) {
			 queryRelations = "MATCH (n:" + nodeId + ") -[r] -> (p) return distinct type(r) AS Relation, labels(p) as Labels";	
		} else {
			queryRelations="match (n:"+nodeId+")-[r]->(p) return distinct type(r) As Relation, labels(p) as Labels, 'OUTGOING' as Direction union MATCH (n:"+nodeId+")<-[k]-(s) return distinct type(k) as Relation, labels(s) as Labels, 'INGOING' as Direction";
		}
		Result result = neo4jOperations.query(queryRelations, new HashMap<String, String>());
		
		return result;
	}
	
	/**
	 * method which queries all relationshiptypes of a certain nodetype
	 * @param nodeId is the nodetype the relationshiptypes are queried for
	 * @return a Result with all relationshiptypes of the nodetype
	 */
	public Result getAllRelationsOfNodeType(String nodeId){
		String queryRelations="match (n:"+nodeId+")-[r]->(p) return distinct type(r) As Relation, labels(p) as Labels, 'OUTGOING' as Direction union MATCH (n:"+nodeId+")<-[k]-(s) return distinct type(k) as Relation, labels(s) as Labels, 'INGOING' as Direction";
		Result result = neo4jOperations.query(queryRelations, new HashMap<String, String>());	
		return result;
	}
	
}
